export const ARTICLE_LIST_REQUEST   = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS   = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAIL      = 'ARTICLE_LIST_FAIL'

export const ARTICLE_LIST_COUNT_REQUEST = 'ARTICLE_LIST_COUNT_REQUEST'
export const ARTICLE_LIST_COUNT_SUCCESS = 'ARTICLE_LIST_COUNT_SUCCESS'
export const ARTICLE_LIST_COUNT_FAIL    = 'ARTICLE_LIST_COUNT_FAIL'

export const ARTICLE_CREATE_REQUEST =   'ARTICLE_CREATE_REQUEST'
export const ARTICLE_CREATE_SUCCESS =   'ARTICLE_CREATE_SUCCESS'
export const ARTICLE_CREATE_FAIL    =   'ARTICLE_CREATE_FAIL'

export const ARTICLE_DETAILS_REQUEST =   'ARTICLE_DETAILS_REQUEST'
export const ARTICLE_DETAILS_SUCCESS =   'ARTICLE_DETAILS_SUCCESS'
export const ARTICLE_DETAILS_FAIL    =   'ARTICLE_DETAILS_FAIL'